SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON

USE master;  
GO 

CREATE DATABASE Reference
GO

USE Reference;  
GO 

CREATE TABLE dbo.Orders
(
	Id int NOT NULL IDENTITY (1, 1),
	ProductId nvarchar(50) NOT NULL,
	Quantity int NOT NULL
)  ON [PRIMARY]
GO

CREATE TABLE dbo.Outbox
(
	Id int NOT NULL IDENTITY (1, 1),
	EventType nvarchar(50) NOT NULL,
	EventValue  NVARCHAR(MAX) NOT NULL
)  ON [PRIMARY]
GO
